"""multi-bottle sessions (lanes)

Revision ID: 02eeb3a2f266
Revises: 6f6d337158f9
Create Date: 2026-10-06 12:17:36.238251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02eeb3a2f266'
down_revision: Union[str, Sequence[str], None] = '6f6d337158f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_bottles',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('machine_id', sa.String(length=32), nullable=False),
    sa.Column('lane', sa.Integer(), nullable=False),
    sa.Column('refund_serial', sa.String(length=64), nullable=True),
    sa.Column('mfg_serial', sa.String(length=64), nullable=True),
    sa.Column('brand', sa.String(length=16), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['rvm_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'lane', name='uq_session_bottle_lane')
    )
    op.create_index(op.f('ix_session_bottles_created_at'), 'session_bottles', ['created_at'], unique=False)
    op.create_index(op.f('ix_session_bottles_session_id'), 'session_bottles', ['session_id'], unique=False)
    # existing rows are single-bottle sessions: lane 1, one bottle
    op.add_column('refund_claims', sa.Column('lane', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('transactions', sa.Column('bottle_count', sa.Integer(), nullable=False, server_default='1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'bottle_count')
    op.drop_column('refund_claims', 'lane')
    op.drop_index(op.f('ix_session_bottles_session_id'), table_name='session_bottles')
    op.drop_index(op.f('ix_session_bottles_created_at'), table_name='session_bottles')
    op.drop_table('session_bottles')
    # ### end Alembic commands ###
