"""bottle evidence photos

Revision ID: 166bf1b8c5b2
Revises: 1cbf1b2ccbc7
Create Date: 2026-10-10 10:34:23.583696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '166bf1b8c5b2'
down_revision: Union[str, Sequence[str], None] = '1cbf1b2ccbc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bottle_evidence',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('machine_id', sa.String(length=32), nullable=False),
    sa.Column('lane', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=64), nullable=False),
    sa.Column('content_type', sa.String(length=32), nullable=False),
    sa.Column('image', sa.LargeBinary(), nullable=False),
    sa.Column('box', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['rvm_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'lane', name='uq_evidence_session_lane')
    )
    op.create_index(op.f('ix_bottle_evidence_created_at'), 'bottle_evidence', ['created_at'], unique=False)
    op.create_index(op.f('ix_bottle_evidence_session_id'), 'bottle_evidence', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bottle_evidence_session_id'), table_name='bottle_evidence')
    op.drop_index(op.f('ix_bottle_evidence_created_at'), table_name='bottle_evidence')
    op.drop_table('bottle_evidence')
    # ### end Alembic commands ###
