"""machine service hours

Revision ID: 1cbf1b2ccbc7
Revises: cc54af816c0a
Create Date: 2026-10-09 15:48:16.329350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cbf1b2ccbc7'
down_revision: Union[str, Sequence[str], None] = 'cc54af816c0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('machines', sa.Column('service_hours', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('machines', 'service_hours')
    # ### end Alembic commands ###
