"""transaction sms_mobile

Revision ID: 5b8b6f2cda0a
Revises: 6c3054b50d67
Create Date: 2026-10-03 12:12:51.885979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b8b6f2cda0a'
down_revision: Union[str, Sequence[str], None] = '6c3054b50d67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('sms_mobile', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'sms_mobile')
    # ### end Alembic commands ###
