"""qr registry

Revision ID: cc54af816c0a
Revises: b0c9ba8d59ed
Create Date: 2026-10-07 12:25:34.594729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc54af816c0a'
down_revision: Union[str, Sequence[str], None] = 'b0c9ba8d59ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qr_codes',
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('raw', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=8), nullable=True),
    sa.Column('serial', sa.String(length=64), nullable=False),
    sa.Column('brand', sa.String(length=16), nullable=True),
    sa.Column('batch', sa.String(length=32), nullable=True),
    sa.Column('label', sa.String(length=120), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('seen_count', sa.Integer(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_machine_id', sa.String(length=32), nullable=True),
    sa.Column('registered_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('code_hash')
    )
    op.create_index(op.f('ix_qr_codes_created_at'), 'qr_codes', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_qr_codes_created_at'), table_name='qr_codes')
    op.drop_table('qr_codes')
    # ### end Alembic commands ###
