"""Generate test refund / manufacturing QR codes and the simulation bottle feed.

Real QR codes are generated by TASMAC; these are only for testing.

    python tools/generate_test_qr.py                 # feed + PNGs for the standard scenarios
    python tools/generate_test_qr.py --count 20      # plus 20 extra valid bottles (PNG only)
"""

import argparse
import random
import sys
from pathlib import Path

import qrcode
import yaml

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from rvm.config import load_config  # noqa: E402
from rvm.services.qr_codec import make_mfg_qr, make_refund_qr  # noqa: E402


def serial(prefix: str) -> str:
    return prefix + "".join(random.choices("0123456789", k=10))


def scenarios(secret: str) -> list[dict]:
    def ok_bottle(name: str, **kw) -> dict:
        b = {
            "name": name,
            "destination": "9876543210@ybl",
            "refund_qr": make_refund_qr(secret, serial("R")),
            "mfg_qr": make_mfg_qr(secret, "KF", "B2610", serial("M")),
        }
        b.update(kw)
        return b

    reused = ok_bottle("reused-refund-qr (2nd use must be rejected)")
    forged = ok_bottle("forged-refund-qr")
    forged["refund_qr"] = forged["refund_qr"][:-4] + "0000"

    return [
        ok_bottle("happy-path-upi", destination="ravi.kumar@okaxis"),
        ok_bottle("happy-path-mobile", destination="+91 98765 43210"),
        ok_bottle("damaged-bottle", condition="damaged"),
        ok_bottle("foreign-object", condition="foreign", refund_qr=None, mfg_qr=None),
        ok_bottle("no-refund-qr", refund_qr=None),
        forged,
        reused,
        {**reused, "name": "reused-refund-qr (second attempt)"},
        ok_bottle("brand-not-eligible", mfg_qr=make_mfg_qr(secret, "XX", "B2610", serial("M"))),
        ok_bottle("payout-pending-then-success", payout="pending_then_success",
                  destination="slow.9876543210@okaxis"),
        ok_bottle("payout-failed", payout="failed", destination="fail.test@okaxis"),
        ok_bottle("customer-walks-away", destination=None),
        ok_bottle("qr-on-back-side", refund_angle=3, mfg_angle=1),
    ]


def save_png(payload: str, path: Path) -> None:
    img = qrcode.make(payload, error_correction=qrcode.constants.ERROR_CORRECT_M)
    img.save(path)


def main() -> None:
    p = argparse.ArgumentParser()
    p.add_argument("--config", default=str(ROOT / "config/machine.sim.yaml"))
    p.add_argument("--out", default=str(ROOT / "test_qr"))
    p.add_argument("--count", type=int, default=0, help="extra valid bottles (PNG only)")
    p.add_argument("--seed", type=int, default=None)
    a = p.parse_args()

    random.seed(a.seed)
    cfg = load_config(a.config)
    secret = cfg.qr.test_signing_secret
    out = Path(a.out)
    out.mkdir(parents=True, exist_ok=True)

    feed = scenarios(secret)
    feed_path = ROOT / "config/sim_bottles.yaml"
    feed_path.write_text(yaml.safe_dump(feed, sort_keys=False, allow_unicode=True), encoding="utf-8")
    print(f"Simulation feed: {feed_path} ({len(feed)} bottles)")

    for i, b in enumerate(feed, 1):
        for kind in ("refund_qr", "mfg_qr"):
            if b.get(kind):
                save_png(b[kind], out / f"{i:02d}_{kind}.png")
    for i in range(a.count):
        save_png(make_refund_qr(secret, serial("R")), out / f"extra_{i:03d}_refund_qr.png")
        save_png(make_mfg_qr(secret, "KF", "B2610", serial("M")), out / f"extra_{i:03d}_mfg_qr.png")
    print(f"QR images: {out}")


if __name__ == "__main__":
    main()
